# Welcome to Jekyll!

title: Lazery Reflections
description: Random thoughts about testing and technology.
baseurl: ""
url: "https://ardesco.lazerycode.com"

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
plugins_dir: jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# About/contact
email: hi@lazeryattack.com
author:
  name: Mark Collin
  contact:
    linkedin: https://www.linkedin.com/in/ardesco/
    github: https://github.com/ardesco
    twitter: https://twitter.com/ardesco

# Page routing
tag_page: '/tags'
category_page: '/categories'
